### ISSUE TITLE
Query protocol

### ISSUE THREAD

**Issue by Nikeron** [mc-server/MCServer#797] opened 2014-03-11 18:51 UTC
Add a Query protocol...

**Comment by madmaxoft** [comment] 2015-01-25 18:54
This should be probably implemented as a separate plugin (once plugins gain the possibility of communicating via UDP).

**Comment by Raekye** [comment] 2015-02-04 01:48
To familiarize myself with lua and the plugin system I just implemented a query server using luasocket. Once the network API + lua api is done I could try and do this

**Comment by madmaxoft** [comment] 2015-02-04 07:29
Nice!
The network API is currently being reviewed, I believe it's ready to be merged in. If you want to give it a try, checkout and build from this PR's branch: #1718
The API itself is not yet properly documented in the LuaAPI docs, but at least there's an example plugin (that I used for debugging) - the NetworkTest.

**Comment by Raekye** [comment] 2015-02-04 16:15
Thanks! I took a look at it yesterday - I'm not too familiar yet, but does it support UDP? I found code/examples relating to TCP

**Comment by madmaxoft** [comment] 2015-02-04 16:18
Right, UDP is not yet supported. Would you like to give us a hand by designing the API? The forum thread is the best place for that: http://forum.mc-server.org/showthread.php?tid=1700

**Comment by Raekye** [comment] 2015-02-04 16:28
Yeah, I just noticed OSSupport/Socket.cpp hardcodes `SOCK_STREAM` when creating a socket. Would love to try helping with the API! Still relatively new to the repository/how things are done, but I'll do what I can. I'm reading through the thread

**Comment by Raekye** [comment] 2015-02-20 23:05
I played around with the stuff on the NetworkUDP branch today and have got this working so far https://github.com/Raekye/MCServer-Query/blob/master/Query.lua

Feedback?

Current implementation:
- Only returns the MOTD, num players, and max players (other values hardcoded to defaults)
- The vanilla implementation ties the challenge token with the requester host and port (and expires after at most 30 seconds). Right now I just use a global challenge token that expires every 30 seconds. Do you think it's important to give everyone different tokens?

**Comment by madmaxoft** [comment] 2015-02-21 08:58
Nice work.

To be honest, I never understood the need for tokens. Why use them at all when anyone can get a new one at any time? It only complicates things and brings nothing of value. So I say, even use a global constant token, no need to expire it.

The settings.ini settings sound like a good idea.

**Comment by Raekye** [comment] 2015-02-21 22:44
I've updated it to use a global challenge token initialized to `os.time()` when it starts. Also made it read the two settings from settings.ini above

I followed [main.lua from the Core plugin](https://github.com/mc-server/Core/blob/master/main.lua#L60) to set default values and rewrite the config file. However, I notice that settings.ini doesn't change (doesn't contain the new values with the defaults)

- If I add the values myself, they are being read (e.g. can disable plugin, change port)
- If I don't add the values myself, but print them out after `GetValueSet(...)` (following the [docs on cIniFile](http://mc-server.xoft.cz/LuaAPI/cIniFile.html), the new values are being listed
- `WriteFile()` returns true (should be successful)

**Comment by LO1ZB** [comment] 2015-02-22 02:14
MCServer supports 1.7.x-1.8.x

**Comment by Raekye** [comment] 2015-02-22 03:05
MCServer supports the protocols for 1.7-1.8, but is that MCServer's version? (Above I just used 1.8 because it's the latest; you could say this is MCServer 1.8 (+ optional patch/build number) which additionally supports protocols 1.7-1.8)

The query could return the supported protocol versions, but if MCServer has hard releases/version/build numbers that might be more appropriate. Both ways, it would be nice to get it from the API, instead of hardcoding the value into the plugin

**Closed** 2015-05-18 20:51 UTC
