### ISSUE TITLE
Client stuck on "Loggin in..." spams errors

### ISSUE THREAD

**Issue by warmist** [mc-server/MCServer#2185] opened 2015-06-01 18:25 UTC
Server prints "Player warmist has joined the game" while client stuck in "Logging in..." screen. Client message log gets spammed with: 

    [21:24:37] [Client thread/FATAL]: Error executing task
    java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask$Sync.innerGet(Unknown Source) ~[?:1.6.0_25]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.6.0_25]
        at g.a(SourceFile:61) [1.8.6.jar:?]
        at ave.av(SourceFile:880) [1.8.6.jar:?]
        at ave.a(SourceFile:325) [1.8.6.jar:?]
        at net.minecraft.client.main.Main.main(SourceFile:124) [1.8.6.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.6.0_25]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.6.0_25]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.6.0_25]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.6.0_25]
        at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
        at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
        at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
        at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
    Caused by: java.lang.NullPointerException
        at bcy.a(SourceFile:600) ~[1.8.6.jar:?]
        at hu.a(SourceFile:41) ~[1.8.6.jar:?]
        at hu.a(SourceFile:8) ~[1.8.6.jar:?]
        at fh$1.run(SourceFile:13) ~[1.8.6.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.6.0_25]
        at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source) ~[?:1.6.0_25]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.6.0_25]
        at g.a(SourceFile:60) ~[1.8.6.jar:?]

**Comment by warmist** [comment] 2015-06-02 11:10
both 64bit and 32bit versions. Very rarely it actually logs-in and then works okay (until next attempt at logging in).

**Comment by madmaxoft** [comment] 2015-06-03 08:19
What client version is that?

**Comment by warmist** [comment] 2015-06-03 09:37
1.8.6 also tested with 1.7.<forgot? was it 10?> basically both newest and one major before that.

**Comment by Zeraceee** [comment] 2015-06-04 23:14
Also having this issue

**Comment by akurei** [comment] 2015-06-06 14:43
I am having the same issue. It just stays at the "Logging in..." screen. I am using 1.8.6.

**Comment by malta108** [comment] 2015-06-07 14:03
Me too. on version 1.8.6 on windows 7

**Comment by bearbin** [comment] 2015-06-07 14:06
Is any error produced on the MCServer console?

**Comment by malta108** [comment] 2015-06-07 14:12
no only on minecraft's console

**Comment by madmaxoft** [comment] 2015-06-08 21:43
I'm still unable to reproduce this on my machines.

OT: @akurei nice Hilbert curve :)

**Comment by Zeraceee** [comment] 2015-06-08 22:30
@madmaxoft latest build, 1.8.6 unmodified client, Windows x64.

**Comment by bearbin** [comment] 2015-06-09 08:10
@madmaxoft, are you using the build from the buildserver?

It could be that the one everyone's using is outdated, because when you switched the windows machines from the old buildserver to the new one it disabled windows builds on the old one. If we changed builds.cuberite.org over to the new one that could fix the problem.

**Comment by madmaxoft** [comment] 2015-06-09 12:33
Buildserver redirection updated.

@warmist , @Zeraceee , @akurei , @malta108 : Please download a new version from http://builds.cuberite.org and retry.

**Comment by akurei** [comment] 2015-06-09 12:47
It is working now. Also the chunk generation is now working properly. In previous versions there were sometimes gaps where chunks would never load.

Off-Topic: @madmaxoft It is not from me but from here http://codegolf.stackexchange.com/questions/22144/images-with-all-colors

**Comment by Seadragon91** [comment] 2015-06-09 15:09
@akurei This error I get, if you don't run MCServer from the directory that contains it.

**Comment by warmist** [comment] 2015-06-09 17:02
Looks like the linked build works okay.

**Comment by bearbin** [comment] 2015-06-09 17:24
Ok, closing.

**Closed by bearbin** 2015-06-09 17:24 UTC
Labels: important
