### ISSUE TITLE
Door drop bug

### ISSUE THREAD

**Issue by falkseidl** [mc-server/MCServer#1981] opened 2015-05-09 17:57 UTC
Destroying the block under a door causes normally that one item of the door will be droped. In MCServer will be two items dropped.
This happens with all types of doors in all gamemodes.

**Comment by wraith11** [comment] 2015-05-11 14:08
Issue is already known. #1327

**Comment by bearbin** [comment] 2015-05-11 15:42
Yep, dupe of #1327

**Closed by bearbin** 2015-05-11 15:42 UTC
