### ISSUE TITLE
Enchanting table bugs

### ISSUE THREAD

**Issue by LO1ZB** [mc-server/MCServer#2003] opened 2015-05-11 20:27 UTC
Im using minecraft 1.8.4 and the newest rev from MCServer
1) place a enchanting table (with bookshelfs around it)
2) enchant someting (in creative mode) without placing lapis in the slot
3) open/close the enchanting gui with random items in the hotpar multiple times
4) move items around in the inventory in the enchanting gui
Sometime an item dissapears, sometime it moves into the laips slot and sometimes an item(stack) gets duplicated

**Comment by Woazboat** [comment] 2015-05-11 21:16
I can reproduce this. 
Alternate between opening your inventory and the gui of the enchanting table. Each time you open the enchanting table gui, all the items in your inventory get shifted one slot to the left. The last item slot in the hotbar gets duplicated, the first item slot in your inventory gets shifted into the lapis slot of the enchanting table. The item in the lapis slot of the enchanting table disappears. 
This only works when you alternate between your inventory and the encahnting table gui. Just opening the enchanting table gui multiple times doesn't work.

In survival mode it gets even weirder:
Items can be duplicated by selecting them and placing them again in the same slot while in the enchanting table gui. Blocks duplicated like that can be placed. The duplicated blocks/items cannot be dropped though and disappear when selected in the inventory.
When clicking on an item in your inventory before opening the enchantment table gui, it gets shifted one slot to the left. Then after clicking on it again in the inventory it sometimes disappears, but it's still somehow in your inventory or being dragged around by your mouse pointer as if selected (it's still invisible). After closing and opening the inventory again and/or possibly after clicking into the inventory again it reappears. 
When you have two stacks of the same item in your inventory while doing the above, the items sometimes stack together when placed near each other.

**Comment by Woazboat** [comment] 2015-05-11 21:29
[72c18a6d88b9c038|23:14:04] HandleRightClick: {-1134, 64, 2247}, face 5, HeldItem: -1:0:0 * 0; dist: 2.52
[72c18a6d88b9c038|23:14:05] WindowClick: WinID 75, SlotNum 29, action: caLeftClick, Item oaklog x 10
[72c18a6d88b9c038|23:14:05] WindowClick: WinID 75, SlotNum -999, action: caLeftPaintBegin, Item -1:0 x 0
[72c18a6d88b9c038|23:14:05] WindowClick: WinID 75, SlotNum 31, action: caLeftPaintProgress, Item -1:0 x 0
[72c18a6d88b9c038|23:14:05] WindowClick: WinID 75, SlotNum -999, action: caLeftPaintEnd, Item -1:0 x 0
[72c18a6d88b9c038|23:14:06] WindowClick: WinID 75, SlotNum 31, action: caLeftClick, Item oaklog x 10
[72c18a6d88b9c038|23:14:06] WindowClick: WinID 75, SlotNum 31, action: caLeftClick, Item -1:0 x 0
[72c18a6d88b9c038|23:14:09] WindowClick: WinID 0, SlotNum 38, action: caLeftClick, Item oaklog x 10
[72c18a6d88b9c038|23:14:09] *** Window lost sync at item 2 in SlotArea with 9 items ***
[72c18a6d88b9c038|23:14:09] My item:    -1:0:0 * 0
[72c18a6d88b9c038|23:14:09] Their item: oaklog:0 * 10

**Comment by madmaxoft** [comment] 2015-05-12 07:10
This is most likely caused by the change in enchanting, that it now requires LapisLazuli, and therefore has an extra slot, compared to earlier clients.

**Comment by bearbin** [comment] 2015-05-12 08:30
Video by @falkseidl 

Video: http://youtu.be/kdIfiwet0R0

**Closed** 2015-05-27 11:21 UTC
