### ISSUE TITLE
Monsters don't attack

### ISSUE THREAD

**Issue by craigwp2703** [mc-server/MCServer#1751] opened 2015-02-18 19:45 UTC
Hi All,

First time getting involved in an open source project so excuse any mistakes. Also, new user of Minecraft!

Anyway, my problem is that all the monsters seem to be harmless. 
They don't attack and I don't take damage when I walk into them. Is there an option I haven't turned on or is there a problem in the code?

Running windows x64 r173.

Thanks!

**Comment by bearbin** [comment] 2015-02-18 20:44
The problem is that MCServer has no AI for monsters, apart from movement (sometimes). I think this issue is a dupe though.

**Comment by craigwp2703** [comment] 2015-02-18 20:46
Ah sorry about the dupe.

I'll look into the AI then, I'm a bit of a programmer anyway, but I'm not promising anything! :)
Thanks for the response

**Comment by bearbin** [comment] 2015-02-18 20:57
Here's a relevant forum thread for you: https://github.com/mc-server/MCServer/issues/910

**Comment by craigwp2703** [comment] 2015-02-18 20:58
Awesome, thanks again!

**Comment by SpockMan02** [comment] 2015-03-24 17:19
For me, hostile mobs walk towards you really fast, then sometimes hit you.. And if they do hit you, you get knocked way back.

**Comment by SafwatHalaby** [comment] 2015-05-09 06:55
This was fixed with the new [AI](http://forum.mc-server.org/showthread.php?tid=1895) and [PathFinder](http://forum.mc-server.org/showthread.php?tid=1571).

Beware that some monsters are still a bit weird, but it's much better now.

**Closed by SafwatHalaby** 2015-05-09 06:55 UTC
Labels: ai
