### ISSUE TITLE
Wolves going under water

### ISSUE THREAD

**Issue by falkseidl** [mc-server/MCServer#2014] opened 2015-05-14 08:54 UTC
I've noticed for some time now, that wolves like it to go underwater. Especially they like it, to standing in 1 block deep water and go around or standing still for some time. Actually, they should drown, or go not into water.

**Comment by SafwatHalaby** [comment] 2015-05-14 09:07
Patience will solve this, the AI and pathfinder are undergoing a big change.
[PathFinder status](http://forum.mc-server.org/showthread.php?tid=1571).
[Mob status](http://forum.mc-server.org/showthread.php?tid=1895.

**Comment by SafwatHalaby** [comment] 2015-05-15 19:59
The general issue is that short mobs have trouble with water. This is identical to #1064

**Comment by bearbin** [comment] 2015-05-15 20:41
Yep, dupe of #1064.

**Closed by bearbin** 2015-05-15 20:41 UTC
Labels: ai
