### ISSUE TITLE
Logout Bug

### ISSUE THREAD

**Issue by falkseidl** [mc-server/MCServer#1974] opened 2015-05-09 09:57 UTC
If a player don't disconnect normaly, but disconnects by closing the window, the player don't leave the server, and others on the server and even the console are not able to kick this ghost player. Other players see the lefted player as a normal one who is not moving.
Also, the ghost player don't disconnects after an amount of time, he is forever online.

Video: 
https://youtu.be/h88mpbLLYTw

**Comment by SafwatHalaby** [comment] 2015-05-09 10:21
Duplicate of #1895

**Closed by SafwatHalaby** 2015-05-09 10:21 UTC
