### ISSUE TITLE
If inventory full, there appears an extra stack in enchantment table

### ISSUE THREAD

**Issue by falkseidl** [mc-server/MCServer#1993] opened 2015-05-10 14:18 UTC
If player have a full inventory, and looks into the enchantment table, one item is in one of the enchantement slots. This happens also in survival gamemode.
Sometime there is a duplication of items.

Video: http://youtu.be/kdIfiwet0R0

**Comment by Woazboat** [comment] 2015-05-11 21:48
Same as #2003. Already did a little research about this bug over there.

**Comment by bearbin** [comment] 2015-05-12 08:29
Dupe of #2003, closing as more discussion is there.

**Closed by bearbin** 2015-05-12 08:29 UTC
