### ISSUE TITLE
Placing beds creates a dupe of the bed

### ISSUE THREAD

**Issue by jammet** [mc-server/MCServer#1886] opened 2015-04-22 05:54 UTC
When a bed is put anywhere in the game world, it will not disappear from the players hand. You can practically "paintbrush" beds all over the place.

**Comment by madmaxoft** [comment] 2015-04-22 06:03
We really need to get working on this, it is the third report already :)
Closing: Duplicate of #1700.

**Closed by madmaxoft** 2015-04-22 06:03 UTC

**Comment by jammet** [comment] 2015-04-22 06:28
^^ My apologies
