### ISSUE TITLE
"Can't connect to sessionserver.mojang.com: SSL handshake failed" causes segfault

### ISSUE THREAD

**Issue by wizardfrag** [mc-server/MCServer#2072] opened 2015-05-19 14:40 UTC
The following are logs from the latest nightly build on Ubuntu 14.04 x86_64
```
     [15:35:20] --- Started Log ---

     [15:35:20] MCServer Jenkins gcc x64 Release (master) build id: #559
     [15:35:20] from commit id: 007bac638bb732aad7ca63dd3e7a79f5dbb9d2b9 built at: Mon May 18 11:01:06 EDT 2015
     [15:35:20] Creating new server instance...
     [15:35:20] Reading server config...
     [15:35:20] Starting server...
info [15:35:20] Compatible clients: 1.7.x, 1.8.x
info [15:35:20] Compatible protocol versions 4, 5, 47
Warn [15:35:20] WebServer: The server is running in unsecured HTTP mode.
info [15:35:20] Put a valid HTTPS certificate in file 'webadmin/httpscert.crt' and its corresponding private key to 'webadmin/httpskey.pem' (without any password) to enable HTTPS support
     [15:35:20] Loaded 407 crafting recipes
     [15:35:20] Loaded 20 furnace recipes and 56 fuels
     [15:35:20] -- Loading Plugins --
     [15:35:20] Initialised Core v.15
     [15:35:20] Initialized TransAPI v.1
     [15:35:20] Initialized ChatLog v.3
     [15:35:20] -- Loaded 3 Plugins --
     [15:35:21] Startup complete, took 721ms!
Warn [15:35:47] SecureRequest: Can't connect to sessionserver.mojang.com: SSL handshake failed: -0x2700
info [15:35:47] Kicking player wizardfrag for "Failed to authenticate account!"
Err  [15:36:48]   D:    | MCServer has encountered an error and needs to close
Err  [15:36:48] Details | SIGSEGV: Segmentation fault
Err  [15:36:48] MCServer Jenkins gcc x64 Release (master) build id: #559
Err  [15:36:48] from commit id: 007bac638bb732aad7ca63dd3e7a79f5dbb9d2b9 built at: Mon May 18 11:01:06 EDT 2015
Err  [15:36:48]   D:    | MCServer has encountered an error and needs to close
Err  [15:36:48] Details | SIGABRT: Server self-terminated due to an internal fault
Err  [15:36:48] MCServer Jenkins gcc x64 Release (master) build id: #559
Err  [15:36:48] from commit id: 007bac638bb732aad7ca63dd3e7a79f5dbb9d2b9 built at: Mon May 18 11:01:06 EDT 2015
```

**Comment by wizardfrag** [comment] 2015-05-19 14:46
gdb output, if required - https://gist.github.com/wizardfrag/19582698486778b1afb5 (gisted to prevent cluttering this issue)

**Comment by Howaner** [comment] 2015-05-19 16:42
Same error.
```
[2428e5f4238e60f9|18:41:29] New ClientHandle created at 0x7f8634012ea0
[593f2da39383c121|18:41:30] Trying to authenticate user Howaner
[593f2da39383c121|18:41:30] SecureRequest: Can't connect to sessionserver.mojang.com: SSL handshake failed: -0x2700
[593f2da39383c121|18:41:30] Kicking player Howaner for "Failed to authenticate account!"
[593f2da39383c121|18:41:30] Sending a DC: "Failed to authenticate account!"
[2428e5f4238e60f9|18:41:30] Client Howaner @ 10.0.237.59 disconnected
[2428e5f4238e60f9|18:41:30] Destroy: client 0x7f8634012ea0, "Howaner"
```

**Comment by bearbin** [comment] 2015-05-19 17:06
Same error. Mojang must have changed something. This is a very important issue since it's affecting everyone.

**Comment by LO1ZB** [comment] 2015-05-19 17:11
I get this error only with 1.7.6 - 1.7.10

**Comment by bearbin** [comment] 2015-05-19 17:11
I get this with 1.8.4

**Comment by worktycho** [comment] 2015-05-19 17:17
Mojang have changed their certificate, and the new certificate has a different root.

**Comment by Pixelfanatic** [comment] 2015-05-19 19:33
yep, same here (1.8.4). Why is this only affecting MCServer, Spigot is still working?!

**Comment by bearbin** [comment] 2015-05-19 19:35
Mojang changed their certificate provider today. We're working on a quick fix which should be out soon.

**Comment by SafwatHalaby** [comment] 2015-05-19 19:53
Should be labeled "ultra important"

**Comment by SphinxC0re** [comment] 2015-05-19 20:01
Importance is importance, no matter how high you push it

**Comment by mayli** [comment] 2015-05-19 20:03
Same here (1.8.4).

```
[19:52:49] MCServer Jenkins gcc x64 Release (master) build id: #560
[19:52:49] from commit id: fff5efedc331922bd871eddef886a75177e67d9a built at: Tue May 19 11:01:01 EDT 2015
[19:52:49] Creating new server instance...
[19:52:49] Reading server config...
[19:52:49] Starting server...
[19:52:49] Compatible clients: 1.7.x, 1.8.x
[19:52:49] Compatible protocol versions 4, 5, 47
[19:52:50] WebServer: The server is running in unsecured HTTP mode.
[19:52:50] Put a valid HTTPS certificate in file 'webadmin/httpscert.crt' and its corresponding private key to 'webadmin/httpskey.pem' (without any password) to enable HTTPS support
[19:52:50] Loaded 407 crafting recipes
[19:52:50] Loaded 20 furnace recipes and 56 fuels
[19:52:50] -- Loading Plugins --
[19:52:50] -- No Plugins Loaded --
[19:52:50] Startup complete, took 895ms!
[20:02:16] SecureRequest: Can't connect to sessionserver.mojang.com: SSL handshake failed: -0x2700
```

**Comment by worktycho** [comment] 2015-05-19 20:30
There is now a temporary hotfix for this in the latest build. Note that it _will_ expose you to MITM attacks.

**Comment by cengizIO** [comment] 2015-05-19 21:36
I hope this gets replaced very soon. Not that anybody is going to be interested in intercepting server traffic to Mojang servers, I'm much more scared if it gets forgotten.

**Comment by worktycho** [comment] 2015-05-20 13:57
We definitely need a new root cert for the server.

**Comment by madmaxoft** [comment] 2015-05-21 08:29
Note that there are two issues here.
First issue is the changed certificate, which causes MCS not to trust the mojang.com servers.
Second issue is the crash caused by this distrust. This seems LibEvent-related and I cannot reproduce this crash on my Windows machine. However, it should still be investigated as it points to a possible problem in the networking code

**Comment by aerique** [comment] 2015-05-21 08:34
I have gotten this crash the first time I ran MCServer but not anymore after that, only "SSL handshake failed".  This was on "Linux raspberrypi 3.18.11+ #781 PREEMPT Tue Apr 21 18:02:18 BST 2015 armv6l GNU/Linux".

Since I no next to nothing about MCServer, I don't know how useful this comment is.

**Comment by SafwatHalaby** [comment] 2015-05-22 13:54
Fixed?

**Comment by bearbin** [comment] 2015-05-22 14:16
Well the thing that caused the crash is fixed, but why a broken root causes a crash is still unsolved AFAIK.

**Comment by jan64** [comment] 2015-05-22 14:55
Still, given the rare nature of a broken root cert i believe this can be marked as non-important now.

**Comment by bearbin** [comment] 2015-05-22 15:06
@jan64 done.

**Comment by jan64** [comment] 2015-05-22 15:29
Thanks

**Closed** 2015-05-23 06:28 UTC

**Comment by nathan130200** [comment] 2022-11-17 20:09
Same problem

```
[17:06:14] --- Started Log ---
[17:06:14] Cuberite AppVeyor (id: 2471)
[17:06:14] from commit a7f287e572866403f1f68984f61b3a650b0e798a built at: 2022-11-15T22:48:44.0000000Z
[17:06:14] Creating new server instance...
[17:06:14] Reading server config...
[17:06:14] Starting server...
[17:06:14] Compatible clients: 1.8.x-1.12.x
[17:06:14] WARNING: BungeeCord is allowed and server set to online mode. This is unsafe and will not work properly. Disable either authentication or BungeeCord in settings.ini.
[17:06:14] WARNING: There is not a Proxy Forward Secret set up, and any proxy server can forward a player to this server unless closed from the internet.
[17:06:14] Loaded 789 crafting recipes
[17:06:14] Loaded 1.12.2 380 recipe book
[17:06:14] Cannot open file "Protocol/1.13/base.recipes.txt", no recipe book recipes will be available!
[17:06:14] Cannot open file "Protocol/1.14.4/base.recipes.txt", no recipe book recipes will be available!
[17:06:14] Could not open the furnace recipes file "furnace.txt". No furnace recipes are available.
[17:06:14] Loaded 49 brewing recipes
[17:06:14] Invalid biome ("BambooJungle") specified in AllowedBiomes in cubeset file Prefabs\SinglePieceStructures\JungleTemple.cubeset. Skipping the biome.
[17:06:14] Invalid biome ("BambooJungleHills") specified in AllowedBiomes in cubeset file Prefabs\SinglePieceStructures\JungleTemple.cubeset. Skipping the biome.
[17:06:14] -- Loading Plugins --
[17:06:14] [Core] Initialised!
[17:06:14] -- Loaded 1 Plugin --
[17:06:14] Startup complete, took 461ms!
[17:06:25] cMojangAPI::SecureRequest: Can't connect to sessionserver.mojang.com: SSL handshake failed: -0x2700```
