### ISSUE TITLE
End world is generating nothing

### ISSUE THREAD

**Issue by falkseidl** [mc-server/MCServer#2013] opened 2015-05-14 08:35 UTC
MCServer is generating end worlds with nothing. The player falls and dies. I tried multiple seeds and builds, no one worked.

Also at /spawn or with some flying around is nothing to find.

Screenshot:
![2015-05-14_10 34 38](https://cloud.githubusercontent.com/assets/5732964/7628547/ea2e8d18-fa24-11e4-9ab3-5a879d3e0e91.png)

**Comment by madmaxoft** [comment] 2015-05-14 08:45
Duplicate of #1627

**Closed by madmaxoft** 2015-05-14 08:45 UTC
