### ISSUE TITLE
MCServer not compiling with GCC 5

### ISSUE THREAD

**Issue by falkseidl** [mc-server/MCServer#2200] opened 2015-06-02 18:39 UTC
The Fedora Linux Distribution recently released a new version, and is now using the GCC 5 compiler. However, MCServer compiling cancels at Authenticator.cpp.o (51%).

```
[ 51%] Building CXX object src/Protocol/CMakeFiles/Protocol.dir/Authenticator.cpp.o
In file included from /mnt/ext/build/mcserver/linux/armv7/master/MCServer/src/../lib/SQLiteCpp/include/SQLiteCpp/Statement.h:16:0,
                 from /mnt/ext/build/mcserver/linux/armv7/master/MCServer/src/../lib/SQLiteCpp/include/SQLiteCpp/Column.h:15,
                 from /mnt/ext/build/mcserver/linux/armv7/master/MCServer/src/../lib/SQLiteCpp/include/SQLiteCpp/Database.h:15,
                 from /mnt/ext/build/mcserver/linux/armv7/master/MCServer/src/Protocol/../RankManager.h:11,
                 from /mnt/ext/build/mcserver/linux/armv7/master/MCServer/src/Protocol/../Root.h:8,
                 from /mnt/ext/build/mcserver/linux/armv7/master/MCServer/src/Protocol/Authenticator.cpp:6:
/mnt/ext/build/mcserver/linux/armv7/master/MCServer/src/../lib/SQLiteCpp/include/SQLiteCpp/Exception.h:53:25: Fehler: expected identifier before »throw«
     #define noexcept    throw()
                         ^
/mnt/ext/build/mcserver/linux/armv7/master/MCServer/src/../lib/SQLiteCpp/include/SQLiteCpp/Exception.h:53:25: Fehler: expected »,« or »...« before »throw«
In file included from /usr/include/c++/5.1.1/stack:61:0,
                 from /mnt/ext/build/mcserver/linux/armv7/master/MCServer/lib/jsoncpp/include/json/reader.h:7,
                 from /mnt/ext/build/mcserver/linux/armv7/master/MCServer/lib/jsoncpp/include/json/json.h:6,
                 from /mnt/ext/build/mcserver/linux/armv7/master/MCServer/src/Protocol/../ClientHandle.h:21,
                 from /mnt/ext/build/mcserver/linux/armv7/master/MCServer/src/Protocol/Authenticator.cpp:8:
/usr/include/c++/5.1.1/bits/stl_stack.h:224:40: Fehler: »swap« als Funktion, die eine Funktion zurückgibt, deklariert
       noexcept(noexcept(swap(c, __s.c)))
                                        ^
/usr/include/c++/5.1.1/bits/stl_stack.h:295:13: Fehler: Initialisierung für Funktion bereitgestellt
     noexcept(noexcept(__x.swap(__y)))
             ^
src/Protocol/CMakeFiles/Protocol.dir/build.make:54: recipe for target 'src/Protocol/CMakeFiles/Protocol.dir/Authenticator.cpp.o' failed
make[2]: *** [src/Protocol/CMakeFiles/Protocol.dir/Authenticator.cpp.o] Error 1
CMakeFiles/Makefile2:1168: recipe for target 'src/Protocol/CMakeFiles/Protocol.dir/all' failed
make[1]: *** [src/Protocol/CMakeFiles/Protocol.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
```

Linux motschegiebchen 4.0.4-301.fc22.armv7hl #1 SMP Thu May 21 14:37:41 UTC 2015 armv7l armv7l armv7l GNU/Linux

cmake version 3.2.2

gcc (GCC) 5.1.1 20150422 (Red Hat 5.1.1-1)

g++ (GCC) 5.1.1 20150422 (Red Hat 5.1.1-1)

**Comment by nounoursheureux** [comment] 2015-06-02 19:07
Duplicate of #2142

**Closed** 2015-06-02 19:18 UTC
